server:
  port: 9001    # 8080留给网关
spring:
  profiles:
    active: dev
  application:
    name: user-service   # 微服务名称
  # 数据库
  datasource:
    url: jdbc:mysql://${shop.db.uri}/shop_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${shop.db.pwd}
    # mysql8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver # mysql8 一下不加 cj

mybatis-plus:
  configuration:
    # mp日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 设置日志级别, ERROR/WARN/INFO/DEBUG,默认info以上显示
logging:
  level:
    root: info

app:
  config:
    api:
      version: v1