shop:
  db:
    uri: ip:port
    pwd: password
  redis:
    host: ip
    port: port
    pwd: password
  rabbitmq:
    host: ip # rabbitMQ的ip地址
    port: port # 端口
    username: name
    password: pwd
aliyun:
  oss:
    endpoint: 1
    access-key-id: 2
    access-key-secret: 3
    bucket-name: 4