server:
  port: 9301    # 8080留给网关
spring:
  profiles:
    active: dev
  application:
    name: order-service   # 微服务名称
  cloud:
    nacos:
      server-addr: 192.168.121.153:8848
  # 数据库
  datasource:
    url: jdbc:mysql://${shop.db.uri}/shop_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${shop.db.pwd}
    # mysql8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver # mysql8 一下不加 cj
  # redis 配置
  redis:
    host: ${shop.redis.host}
    port: ${shop.redis.port}
    password: ${shop.redis.pwd}
mybatis-plus:
  configuration:
    # mp日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 设置日志级别, ERROR/WARN/INFO/DEBUG,默认info以上显示
logging:
  level:
    root: info

app:
  config:
    api:
      version: v1

# aliyunOSS
aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}
    access-key-id: ${aliyun.oss.access-key-id}
    access-key-secret: ${aliyun.oss.access-key-secret}
    bucket-name: ${aliyun.oss.bucket-name}
feign:
  okhttp:
    enabled: true  # 开启连接池支持

#seata:
#  tx-service-group: ${spring.application.name}-group
#  service:
#    grouplist:
#      shop: 192.168.121.153:8099
#    vgroup-mapping:
#      order-service-group: shop