shop:
  db:
    uri: ip:port
    pwd: password
  redis:
    host: ip
    port: port
    pwd: password
  rabbitmq:
    host: ip # rabbitMQ的ip地址
    port: port # 端口
    username: name
    password: pwd
    virtual-host: /
aliyun:
  oss:
    endpoint: 1
    access-key-id: 2
    access-key-secret: 3
    bucket-name: 4
# AliPay
alipay:
  config:
    appid: appid
    private-key: private-key
    alipay-public-key: alipay-public-key
    notify-url: notify-url
    return-url: return-url